### ISSUE TITLE
Panic with HEAD requests when any other route contains a param

### ISSUE THREAD

**Issue by ernestoalejo** [husobee/vestigo#23]
**main.go**
```go
package main

import (
	"net/http"
	"log"
	
	"github.com/husobee/vestigo"
)

func main() {
	router := vestigo.NewRouter()
	router.Get("/:param/foo", func(w http.ResponseWriter, r *http.Request) {})

	http.Handle("/", router)
	log.Fatal(http.ListenAndServe(":9000", router))
}
```

**Commands**
```shell
go run main.go
curl -I localhost:9000/foo
```

**Result**
```
2016/06/22 18:11:42 http: panic serving 127.0.0.1:36656: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc820072100)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x728500, 0xc82000a130)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/husobee/vestigo.glob.func2.1(0x7fa51cd6c8c8, 0xc820075a00, 0xc8200dc000)
	/home/ernesto/goprojects/src/github.com/husobee/vestigo/handlers.go:41 +0x138
github.com/husobee/vestigo.glob.func6.1(0x7fa51cd6c8c8, 0xc820075a00, 0xc8200dc000)
	/home/ernesto/goprojects/src/github.com/husobee/vestigo/handlers.go:112 +0x3e7
github.com/husobee/vestigo.(*Router).ServeHTTP(0xc82000aef0, 0x7fa51cd6c8c8, 0xc820075a00, 0xc8200dc000)
	/home/ernesto/goprojects/src/github.com/husobee/vestigo/router.go:54 +0x52
net/http.serverHandler.ServeHTTP(0xc820072080, 0x7fa51cd6c8c8, 0xc820075a00, 0xc8200dc000)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820072100)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

If the route is replaced with `router.Get("/foo", func(w http.ResponseWriter, r *http.Request) {})` there is no error. If it's replaced with `router.Get("/bar", func(w http.ResponseWriter, r *http.Request) {})` the expected 404 error is returned.

**Comment by husobee** [comment]
@ernestoalejo: here is a PR with a fix to this problem -> https://github.com/husobee/vestigo/pull/24

This problem is due to the headHandler calling the get handler for that particular node.  If there is no handler, (because the node doesnt have a get handler) it tries to run the nil function.  Please let me know if this PR fixes this issue, and I will get it merged in.

**Comment by ernestoalejo** [comment]
I can confirm the change fixes the issue. Thanks for the quick patch!

**Comment by husobee** [comment]
https://github.com/husobee/vestigo/pull/24 has been merged with this fix.  Feel free to close this issue.
